const CITIES = [
	{ id: 1, city: 'Algiers', shift: 0 },
	{ id: 2, city: 'Adelajda', shift: 7 },
	{ id: 3, city: 'Amsterdam', shift: -1 },
	{ id: 4, city: 'Ankara', shift: 1 },
	{ id: 5, city: 'Ateny', shift: 1 },
	{ id: 6, city: 'Atlanta', shift: -6 },
	{ id: 7, city: 'Bagdad', shift: 1 },
	{ id: 8, city: 'Baku', shift: 2 },
	{ id: 9, city: 'Bangkok', shift: 5 },
	{ id: 10, city: 'Barcelona', shift: 0 },
	{ id: 11, city: 'Beirut', shift: 1 },
	{ id: 12, city: 'Berlin', shift: 0 },
	{ id: 13, city: 'Boston', shift: 0 },
	{ id: 14, city: 'Brasilia', shift: -5 },
	{ id: 15, city: 'Bruksela', shift: 0 },
	{ id: 16, city: 'Bukareszt', shift: 1 },
	{ id: 17, city: 'Budapeszt', shift: 0 },
	{ id: 18, city: 'Buenos Aires', shift: -5 },
	{ id: 19, city: 'Chicago', shift: -7 },
	{ id: 20, city: 'Delhi', shift: 3 },
	{ id: 21, city: 'Dubaj', shift: 2 },
	{ id: 22, city: 'Dublin', shift: -1 },
	{ id: 23, city: 'Hawana', shift: -6 },
	{ id: 24, city: 'Helsinki', shift: 1 },
	{ id: 25, city: 'Hong Kong', shift: 6 },
	{ id: 26, city: 'Honolulu', shift: -12 },
	{ id: 27, city: 'Huston', shift: -7 },
	{ id: 28, city: 'Jerozolima', shift: 1 },
	{ id: 29, city: 'Kabul', shift: 2 },
	{ id: 30, city: 'Kopenchaga', shift: 0 },
	{ id: 31, city: 'Kuala Lumpur', shift: 6 },
	{ id: 32, city: 'Kuweit', shift: 1 },
	{ id: 33, city: 'La Paz', shift: -6 },
	{ id: 34, city: 'Las Vegas', shift: -9 },
	{ id: 35, city: 'Lisbona', shift: -1 },
	{ id: 36, city: 'Londyn', shift: -1 },
	{ id: 37, city: 'Los Angeles', shift: -9 },
	{ id: 38, city: 'Madryt', shift: 0 },
	{ id: 39, city: 'Meksyk', shift: -7 },
	{ id: 40, city: 'Miami', shift: 6 },
	{ id: 41, city: 'Moskwa', shift: 1 },
	{ id: 42, city: 'Mumbaj (Bombaj)', shift: 3 },
	{ id: 43, city: 'Nairobi', shift: 1 },
	{ id: 44, city: 'Nowy York', shift: -6 },
	{ id: 45, city: 'Odessa', shift: 1 },
	{ id: 46, city: 'Oslo', shift: 0 },
	{ id: 47, city: 'Paryż', shift: 0 },
	{ id: 48, city: 'Praga', shift: 0 },
	{ id: 49, city: 'Reykjavik', shift: -2 },
	{ id: 50, city: 'Rio de Janeiro', shift: -5 },
	{ id: 51, city: 'Ryga', shift: 1 },
	{ id: 52, city: 'Rzym', shift: 0 },
	{ id: 53, city: 'San Francisco', shift: -7 },
	{ id: 54, city: 'San Salvador', shift: 8 },
	{ id: 55, city: 'Sao Paulo', shift: -5 },
	{ id: 56, city: 'Seatle', shift: -9 },
	{ id: 57, city: 'Seul', shift: 7 },
	{ id: 58, city: 'Shanghaj', shift: 6 },
	{ id: 59, city: 'Sztokholm', shift: 6 },
	{ id: 60, city: 'Sydney', shift: 8 },
	{ id: 61, city: 'Tajpej', shift: 6 },
	{ id: 62, city: 'Tallinn', shift: 1 },
	{ id: 63, city: 'Tokio', shift: 7 },
	{ id: 64, city: 'Toronto', shift: -6 },
	{ id: 65, city: 'Vancouver', shift: -9 },
	{ id: 66, city: 'Warszawa', shift: 0 },
	{ id: 67, city: 'Waszyngton', shift: -6 },
	{ id: 68, city: 'Wilno', shift: 1 },
	{ id: 69, city: 'Zagrzeb', shift: 0 },
	{ id: 70, city: 'Zurych', shift: 0 },
];

export default CITIES;
export {};
