const CITIES = [
    {id: 1, city: 'Algiers', shift: 0},
    {id: 2, city: 'Amsterdam', shift: -1},
    {id: 3, city: 'Ankara', shift: 1},
    {id: 4, city: 'Ateny', shift: 1},
    {id: 5, city: 'Atlanta', shift: -6},
    {id: 6, city: 'Bagdad', shift: 1},
    {id: 7, city: 'Bangkok', shift: 5},
    {id: 8, city: 'Barcelona', shift: 0},
    {id: 9, city: 'Beirut', shift: 1},
    {id: 10, city: 'Boston', shift: 0},
    {id: 11, city: 'Brasilia', shift: -5},
    {id: 12, city: 'Bukareszt', shift: 1},
    {id: 13, city: 'Budapeszt', shift: 0},
    {id: 14, city: 'Buenos Aires', shift: -5},
    {id: 15, city: 'Chicago', shift: -7},
    {id: 16, city: 'Dubaj', shift: 2},
    {id: 17, city: 'Dublin', shift: -1},
    {id: 18, city: 'Hawana', shift: -6},
    {id: 19, city: 'Helsinki', shift: 1},
    {id: 20, city: 'Hong Kong', shift: 6},
    {id: 21, city: 'Honolulu', shift: -12},
    {id: 22, city: 'Huston', shift: -7},
    {id: 23, city: 'Jerozolima', shift: 1},
    {id: 24, city: 'Kabul', shift: 2},
    {id: 25, city: 'Kopenchaga', shift: 0},
    {id: 26, city: 'Kuala Lumpur', shift: 6},
    {id: 27, city: 'Kuweit', shift: 1},
    {id: 28, city: 'La Paz', shift: -6},
    {id: 29, city: 'Las Vegas', shift: -9},
    {id: 30, city: 'Lisbona', shift: -1},
    {id: 31, city: 'Londyn', shift: -1},
    {id: 32, city: 'Los Angeles', shift: -9},
    {id: 33, city: 'Madryt', shift: 0},
    {id: 34, city: 'Meksyk', shift: -7},
    {id: 35, city: 'Miami', shift: 6},
    {id: 36, city: 'Moskwa', shift: 1},
    {id: 37, city: 'Nairobi', shift: 1},
    {id: 38, city: 'Nowy York', shift: -6},
    {id: 39, city: 'Oslo', shift: 0},
    {id: 40, city: 'Paryż', shift: 0},
    {id: 41, city: 'Praga', shift: 0},
    {id: 42, city: 'Reykjavik', shift: -2},
    {id: 43, city: 'Rio de Janeiro', shift: -5},
    {id: 44, city: 'Rzym', shift: 0},
    {id: 45, city: 'San Francisco', shift: -7},
    {id: 46, city: 'San Salvador', shift: 8},
    {id: 47, city: 'Sao Paulo', shift: -5},
    {id: 48, city: 'Seatle', shift: -9},
    {id: 49, city: 'Seul', shift: 7},
    {id: 50, city: 'Shanghaj', shift: 6},
    {id: 51, city: 'Sztokholm', shift: 6},
    {id: 52, city: 'Sydney', shift: 8},
    {id: 53, city: 'Tajpej', shift: 6},
    {id: 54, city: 'Tallinn', shift: 1},
    {id: 55, city: 'Tokio', shift: 7},
    {id: 56, city: 'Toronto', shift: -6},
    {id: 57, city: 'Vancouver', shift: -9},
    {id: 58, city: 'Warszawa', shift: 0},
    {id: 59, city: 'Waszyngton', shift: -6},
    {id: 60, city: 'Zagrzeb', shift: 0},
    {id: 61, city: 'Zurych', shift: 0},
];

export default CITIES;
export{}